---
version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: daily
      timezone: "Asia/Tokyo"
    labels:
      - dependabot
    pull-request-branch-name:
      separator: "_"
    commit-message:
      prefix: "chore(dependabot): "
